services:
  postgres:
    env_file:
      - ./.env
    image: postgres
    container_name: ${POSTGRES_CONTAINER}
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  
  app:
    env_file:
      - ./.env
    build:
      context: ./app
      dockerfile: ../Dockerfile
    container_name: ${APP_CONTAINER}
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - postgres
    restart: always

volumes:
  db-data:
    driver: local